django_app/urls.py
from django.urls import include, path
from django.contrib import admin
from django.urls import path, include, re_path
from .views import FrontendAppView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("cars/", include("cars.urls")),
    # path('polls/', include('polls.urls')),
    path('api/users/', include('users.urls')),
    path('api/data/', include('hackernews.urls')),  # add this line
    re_path(r'^', FrontendAppView.as_view()),
]

hackernews/urls.py
from django.urls import path
from django.conf.urls import url, include
import rest_framework
from rest_framework import urlpatterns

from . import views

from rest_framework import routers
from .api import NewspostViewSet, CommentViewSet


router = routers.SimpleRouter()
# router.register('/', views.index, 'index')
router.register(r'news', NewspostViewSet)
# router.register('api/comment(?P<postId>\d+)', CommentSearchSet, 'comments')
router.register(r'comment', CommentViewSet)
# router.register('^api/comment/(?P<postId>.+)/$',
# CommentListViewSet, 'commentList')
# re_path('^purchases/(?P<username>.+)/$', PurchaseList.as_view()),


# urlpatterns = router.urls

app_name = 'hackernews'
urlpatterns = [
    path('', include(router.urls)),
    # path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('new-post/', views.newPost, name='newPost'),
    path('login/', views.userLogin, name='userLogin'),
    path('logout/', views.userLogout, name='userLogout'),
    # url(r'^', include(router.urls), name='routerurls'),
    # path('api/', include(router.urls)),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

# urlpatterns += router.urls

users/urls.py
from django.urls import include, path
urlpatterns = [
    path('auth/', include('rest_auth.urls')),
    path('auth/register/', include('rest_auth.registration.urls'))
]

hackernews/models.py
from django.db import models

# Create your models here.
# from django.contrib.auth.models import User
# from django.contrib.postgres.fields import ArrayField

# from django.db.models.signals import post_save
# from django.dispatch import receiver

from users.models import CustomUser


class Newspost(models.Model):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200, blank=True)
    text = models.CharField(max_length=2500, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    point = models.IntegerField(default=0)
    author = models.ForeignKey(
        CustomUser, on_delete=models.DO_NOTHING, default='')

    class Meta:
        ordering = ('pub_date',)


class Comment(models.Model):
    newspost = models.ForeignKey(
        Newspost, on_delete=models.SET_DEFAULT, default='<anonymous>')
    text = models.CharField(max_length=2000)
    comment_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        CustomUser, on_delete=models.SET_DEFAULT, default='<anonymous>')
    # replies = models.JSONField()
    replyTo = models.ForeignKey(
        'Comment', on_delete=models.CASCADE, null=True, blank=True)
    hasReplies = models.BooleanField(default=False)
    # replyFor = models.ForeignKey(
    #     'Comment', on_delete=models.CASCADE)

    @property
    def customuser(self):
        return self.user.username

    class Meta:
        ordering = ('comment_date',)


# building on django user model


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     favorites = ArrayField(models.IntegerField(default=0), default=list)


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)


# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

hackernews/forms.py
from .models import Newspost, Comment

from django.forms import ModelForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# class UserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'password1', 'password2']


class NewspostForm(ModelForm):
    class Meta:
        model = Newspost
        fields = ['title', 'url']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['newspost']

# class UserOwnForm(ModelForm):
#     class Meta:
#         model = UserOwn
#         fields = ['username', 'password']

hackernews/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpResponse
from .models import Newspost
from .forms import NewspostForm

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm  # add this
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from django.utils import timezone


def index(request):
    newsposts = Newspost.objects.all().order_by('-pub_date')
    # newsposts = {v: k for k, v in newsposts.items()}
    context = {'newsposts': newsposts}
    return render(request, 'hackernews/index.html', context)


def userLogin(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        print('login-form-validation: ', form.is_valid())
        # print('password: ', form)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print('password: ', password)
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("hackernews:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
        return redirect("hackernews:index")
    # return HttpResponse('you wanna login')


def userLogout(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("hackernews:index")


def newPost(request):
    if (request.method == 'POST'):
        if request.user.is_authenticated:
            f = NewspostForm(request.POST)
            print(f.is_valid())
            print(f.cleaned_data)
            if f.is_valid():
                obj = f.save(commit=False)
                # obj.pub_date = timezone.now()
                obj.author = request.user
                obj.save()
                messages.info(request, "You have successfully posted.")
                return redirect('hackernews:index')
                print(obj)
            else:
                messages.error(request, "Please fill all the fields.")
        else:
            messages.error(request, "Please login.")
        return redirect('hackernews:newPostFormRender')
    else:
        return render(request, 'hackernews/new_post.html')


def signup(request):
    if (request.method == 'POST'):
        form = UserCreationForm(request.POST)
        print('form is valid: ', form.is_valid())
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successfull")
            return redirect('hackernews:index')
        messages.error(request, "Registration error.")
        return render(request, 'hackernews/signup.html', {'form': form})
    form = UserCreationForm()
    return render(request, 'hackernews/signup.html', {'form': form})

hackernews/templates/hackernews/boilerplate.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News</title>
</head>

<body>

    {% if user.is_authenticated %}

    <li class="nav-item">
        <a class="nav-link" href="{% url 'hackernews:userLogout' %}">Logout</a>
    </li>
    <li class="nav-item">
        <!-- <a class="nav-link" href="">Welcome, {{user.username}}</a> -->
        Welcome, {{user.username}}

    </li>
    <br>
    {% else %}

    <div>
        <form action="{% url 'hackernews:userLogin' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input id="username" name="username" type="text">
            <label for="password">Password</label>
            <input id="password" name="password" type="password">
            <button>Login</button>
        </form>
    </div>
    {% endif %}
    <!-- <br> -->
    <div>
        <a href="{% url 'hackernews:index' %}">Home</a>
        <a href="{% url 'hackernews:newPost' %}">New</a>
        <a href="{% url 'hackernews:signup' %}">Register</a>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <body>
        <!-- <div id="sidebar">
            {% block sidebar %}
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/blog/">Blog</a></li>
            </ul>
            {% endblock %}
        </div> -->

        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </body>

</body>

</html>

hackernews/templates/hackernews/index.html
{% extends "hackernews/boilerplate.html" %}

{% block content %}

{% if newsposts %}
<ul>
    {% for post in newsposts %}
    <li><a href="{% url 'hackernews:index' %}">{{post.title}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No post is available.</p>
{% endif %}

{% endblock %}

hackernews/templates/hackernews/new_post.html
{% extends "hackernews/boilerplate.html" %}

{% block content %}
<br>
<form action="{% url 'hackernews:newPost' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title</label>
    <input id="title" name="title" type="text">
    <label for="url">Url</label>
    <input id="url" name="url" type="text">
    <button>Submit</button>
</form>

{% endblock %}

hackernews/templates/hackernews/register.html
{% extends "hackernews/boilerplate.html" %}

{% block content %}
<form action="{% url 'hackernews:newUserSave' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username</label>
    <input id="username" name="username" type="text">
    <!-- <label for="email">Email</label>
    <input id="email" name="email" type="text"> -->
    <label for="password1">Password</label>
    <input id="password1" name="password1" type="password">
    <label for="password2">Re-Password</label>
    <input id="password2" name="password2" type="password">
    <button>Submit</button>
</form>
{% endblock %}

hackernews/templates/hackernews/signup.html
{% extends "hackernews/boilerplate.html" %}

{% block content %}

<h2>Sign up Form</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Sign up</button>
</form>

{% endblock %} q